### ISSUE TITLE
Bug on latest master with debugging on

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_heartbeat#144] opened 2023-10-09 05:59 UTC
<div class="notifytiny debuggingmessage" data-rel="debugging">Inclusion of lib/cronlib.php is no longer required. Please update your code to use the new \core\cron class.<ul style="text-align: left" data-rel="backtrace"><li>line 31 of /lib/cronlib.php: call to debugging()</li><li>line 37 of /admin/tool/heartbeat/classes/check/tasklatencycheck.php: call to require_once()</li><li>line 145 of /lib/classes/component.php: call to include_once()</li><li>line 33 of /admin/tool/heartbeat/lib.php: call to core_component::classloader()</li><li>line 107 of /lib/classes/check/manager.php: call to tool_heartbeat_status_checks()</li><li>line 56 of /lib/classes/check/manager.php: call to core\check\manager::get_status_checks()</li><li>line 284 of /admin/tool/heartbeat/croncheck.php: call to core\check\manager::get_checks()</li></ul></div>

WARNING: 2 status checks have reported warnings or errors: 
Cron running
There was 3 days 1 hour between the last two runs of the cron maintenance script
and it should run every 1 min. We recommend configuring it to run more
frequently.
Details: https://master.localhost/report/status/index.php?detail=tool_task_cronrunning
https://master.localhost/admin/tool/task/runningtasks.php

Ad hoc task queue
Oldest unprocessed task is 3 days 1 hour, which is more than 4 hours
Details: https://master.localhost/report/status/index.php?detail=tool_task_adhocqueue
 (Checked Oct 9 06:57:42)

**Comment by matthewhilton** [comment] 2023-10-09 21:41
Probably duplicate of https://github.com/catalyst/moodle-tool_heartbeat/issues/143 (in unit tests, but same root cause)

**Closed** 2023-10-09 23:36 UTC
